name: Analyze Commit Messages
on: [pull_request]

permissions:
  pull-requests: write
  contents: write
jobs:
  analyze-commits:
    name: Analyze commits
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/analyze-commits.yml@v1
    with:
      previewNotes: false

  preview-changeset:
    name: Preview changeset
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/preview-changeset-release.yml@v1
    with:
      pr-title: ${{ github.event.pull_request.title }}
